2018-11-28 16:32:09,238 - __main__ - INFO - Hello baby
2018-11-28 16:34:50,884 - __main__ - INFO - Hello baby
2018-11-28 16:50:23,559 - __main__ - INFO - Hello baby
2018-11-28 16:50:23,560 - __main__ - ERROR - Failed to do something
Traceback (most recent call last):
  File "./logging_test.py", line 53, in <module>
    print(1/0)
ZeroDivisionError: division by zero
2018-11-28 16:52:31,586 - __main__ - INFO - Hello baby
2018-11-28 16:52:31,588 - __main__ - ERROR - Failed to do something
Traceback (most recent call last):
  File "./logging_test.py", line 53, in <module>
    print(1/0)
ZeroDivisionError: division by zero
